import { SaffronProduct, BatchAnalysis } from './types';

// Helper to convert English digits to Persian digits
export function toPersianDigits(n: number | string): string {
  const farsiDigits = ['۰', '۱', '۲', '۳', '۴', '۵', '۶', '۷', '۸', '۹'];
  return n
    .toString()
    .replace(/\d/g, (x) => farsiDigits[parseInt(x, 10)]);
}

// Format numbers with commas in Persian
export function formatToman(amount: number): string {
  const formatted = amount.toLocaleString('en-US');
  return toPersianDigits(formatted);
}

export const SAFFRON_PRODUCTS: SaffronProduct[] = [
  {
    id: 'zr-crystal-1m',
    name: 'زعفران سوپر نگین ۱ مثقال جام کریستال',
    category: 'super-negin',
    categoryLabel: 'سوپر نگین صادراتی',
    badge: 'تخفیف ویژه پاییزه',
    batchCode: 'ZR-2024-N1',
    price: 890000,
    originalPrice: 980000,
    weightGrams: 4.608,
    weightLabel: '۱ مثقال (۴.۶ گرم)',
    rating: 4.9,
    reviewsCount: 142,
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuD5xZJIz_rRW1UpxX2mfjey3x7SYX2PHx9jvwjeW5Gn6NHYG8v8NvJwGnsHKqmhUqLR3B3QZHtKgmf-xIMnfjZqn6RsyjarRONPkEPTH_h2nxmB-7kMrScYDeOYn9ibELlNSpnJkE27pztflP6B5NZ7qEgX1M-irsYvrGySb6SjbZWtrWiCGYK9em9dQ0B6KJy_yI6I17GkaK7XDpZaFqPcGF5jNNcOceO6SL3ubFgP8gNVUtP42j_N1A',
    description: 'کلاله‌های سه شاخه درشت سوپر نگین اتویی قائنات، بدون کوچک‌ترین خامه سفید، در ظرف کریستال شش ضلعی با چوب‌پنبه طبیعی ضد خروج عطر.',
    packagingType: 'شیشه کریستال تراش‌خورده با چوب‌پنبه پرتغالی',
    crocinLevel: 294.6,
    safranalLevel: 38.4,
    picrocrocinLevel: 92.1,
    origin: 'مزارع کوهپایه‌ای قائنات (روستای اسفدن)',
    harvestYear: '۱۴۰۳ (برداشت امسال)',
    inStock: true,
  },
  {
    id: 'zr-gift-shahnashin',
    name: 'پک هدیه فاخر شاه‌نشین (۲ مثقال + هاون برنجی)',
    category: 'gift-box',
    categoryLabel: 'پک کادویی و تشریفات',
    badge: 'پک نفیس سلطنتی',
    batchCode: 'ZR-GIFT-SH',
    price: 2450000,
    originalPrice: 2700000,
    weightGrams: 9.2,
    weightLabel: '۲ مثقال (۹.۲ گرم)',
    rating: 5.0,
    reviewsCount: 89,
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAkyOnzMzG4Ry_4jIFzaVkoVKL0Jvp58YTwH8kTDY3EabmZiEfdSEy6Mw_y9Q0Dfgnw3qN8UZep5dt_XvJ9H90-6XjsajTlZr28YouHNOBs6Veix0Zme_NBPNYmJjVxBCtSg4CR7Zif0mwsRuyKzFziZS-JhaI8pGf1v56p_x2ov0T3a1hJFMjiQxkGI1XnVRVdcEivOs502ixG665N7fHCb4WjPJBByIz9_RNKnKOu2PdcAcwTCFfzNg',
    description: 'جعبه نفیس چوبی منقش به نگارگری مینیاتور دوره صفوی، شامل دو عدد شیشه کریستال سوپر نگین، یک عدد هاون برنجی قلم‌زنی دست‌ساز و قاشقک زرین.',
    packagingType: 'باکس چوبی مینیاتور دست‌ساز + مخمل‌کوبی داخل',
    crocinLevel: 292.0,
    safranalLevel: 39.0,
    picrocrocinLevel: 94.0,
    origin: 'قائنات - خراسان جنوبی',
    harvestYear: '۱۴۰۳',
    inStock: true,
  },
  {
    id: 'zr-sargol-1g',
    name: 'زعفران سرگل ممتاز ۱ گرمی پاکتی',
    category: 'sargol',
    categoryLabel: 'سرگل ممتاز',
    badge: 'اقتصادی و روزمره',
    batchCode: 'ZR-SR-01G',
    price: 210000,
    originalPrice: 230000,
    weightGrams: 1.0,
    weightLabel: '۱ گرم خالص',
    rating: 4.8,
    reviewsCount: 310,
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDjxckDZY4gFF4kP9bKdcYzkD0DO-IttZjoNUeO1TO4suU045tcjBjSWUGvsXjqGaiRmTjqrxm52I-vIHGDk4EhiCvHQn_rYsVaCQoMoyZGUk1aI8UiUxkCsXqAh21P65fg62MuzqQA1wkQVP4t0HnH0SX7cQVyxFp-YCLqTVpRfuY3wVEQ7SxXZnJIhgm-bwUO-yLEgVpIZsyb4xzaMosLeK4z3WOFTPy7WgOoU-5sGrlGqfvu9V5V0A',
    description: 'زعفران سرگل دست‌چین شده با عطر زنده و غلیظ در پاکت متالایز چندلایه ضداکسیداسیون؛ مناسب برای مصارف خانگی، پلوهای مجلسی، چای و دسر.',
    packagingType: 'پاکت متالایز سوپاپ‌دار طلاکوب',
    crocinLevel: 272.5,
    safranalLevel: 36.8,
    picrocrocinLevel: 88.0,
    origin: 'قائنات - مزارع دیم',
    harvestYear: '۱۴۰۳',
    inStock: true,
  },
  {
    id: 'zr-vip-5m',
    name: 'جعبه خاتم و معرق چوبی صادراتی ۵ مثقال',
    category: 'gift-box',
    categoryLabel: 'پک کادویی و تشریفات',
    badge: 'صادراتی VIP',
    batchCode: 'ZR-BOX-VIP5',
    price: 4600000,
    originalPrice: 5100000,
    weightGrams: 23.0,
    weightLabel: '۵ مثقال (۲۳ گرم)',
    rating: 5.0,
    reviewsCount: 47,
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCtW4KXwvv-57rgemzwhOhNnQ1k74AQB1wQpY6sD9utLRwMy59EGq4RDdrBHVZDrkYHdO08mP1MSZuwkzpy1pIhK0ly_gxO7Yj2YtEfp3IigNZ_cwIveXc7MSPbFRltkibmQ2lDd-BIW268b77X0a4GG6C7qpjNfuSx7muKemR203t4SdAcqv3iLU6dRajVKcYsKVYk9BcLLS-HeljAOkA2SMIJf3N7Yxy0Cqizm4f-Y1Vd8uLE6dxooA',
    description: 'شاهکار صنایع دستی خاتم‌کاری و معرق اصفهان با روکش پلی‌استر براق، محتوی ۵ مثقال سوپر نگین گرید A++ در ظروف شیشه‌ای اشکی ضد ضربه.',
    packagingType: 'جعبه تمام چوب معرق و خاتم با قفل برنجی کهنه‌نما',
    crocinLevel: 298.2,
    safranalLevel: 41.0,
    picrocrocinLevel: 96.5,
    origin: 'قائنات - مزارع ممتاز',
    harvestYear: '۱۴۰۳',
    inStock: true,
  },
  {
    id: 'zr-super-negin-half',
    name: 'زعفران سوپر نگین نیم مثقال خاتم سنتی',
    category: 'super-negin',
    categoryLabel: 'سوپر نگین صادراتی',
    badge: 'بسته‌بندی سنتی',
    batchCode: 'ZR-2024-NH',
    price: 475000,
    originalPrice: 520000,
    weightGrams: 2.3,
    weightLabel: 'نیم مثقال (۲.۳ گرم)',
    rating: 4.8,
    reviewsCount: 95,
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCp3KyQteVRY8M2G69xmapXzNojstXkqh1_tC5jLnc8LhCiC8GwHbi4Eawynu8FOSW9UwkjReYqlANSM4d_WCuBl69LQfWlvLREptynob6X0W9oPDpsFJTZ53WuFcD0oYoF7lzd3NkazXk7ic20ceQ2M5mvuc-67PM7dif4yMOn7fV857M3t733gduOQ5qhkYQSnrnLmsb6ntRIyY37RXucnT8cs5SGSXpfwmu5cIPbKDq3lTeCD3nfiw',
    description: 'ظرف فلزی طرح خاتم سنتی با طلق شفاف برای نمایش کلاله‌های قلم‌درشت و اتویی سوپر نگین زرین. محافظت کامل در برابر خرد شدن و نور.',
    packagingType: 'ظرف فلزی طرح خاتم سنتی با عایق رطوبت',
    crocinLevel: 291.4,
    safranalLevel: 37.9,
    picrocrocinLevel: 91.0,
    origin: 'قائنات - خراسان جنوبی',
    harvestYear: '۱۴۰۳',
    inStock: true,
  },
  {
    id: 'zr-brass-mortar',
    name: 'هاون برنجی دست‌ساز قلم‌زنی سنتی',
    category: 'accessory',
    categoryLabel: 'ملزومات دم‌آوری',
    badge: 'دست‌ساز اصیل',
    batchCode: 'ZR-ACC-M1',
    price: 390000,
    originalPrice: 450000,
    weightGrams: 350,
    weightLabel: '۳۵۰ گرم برنج خالص',
    rating: 4.9,
    reviewsCount: 63,
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAXKzquvw2R6VExceef3EvFCAe1yDv9cm5IHy6Bb7ZmTaGDGxOwLGqF-4f0Oebq7o6VfRfrjItnuRVfYjc2-xgupaCMUuwVDLPD7aPKPWGu8eoBpBwnlabv1T_mGCz-DKDnDQI0Sw7WmWRErCZ1hq_-WYbGj1qb9YBR0dSX9_Zq-H3ePFjAgnoIVDqBGjsol25JT1UdOBBuYnzkgWIfleYZzeYRnnGvRWrzeyajkPcGq1n5PuB5bRwtww',
    description: 'تراشیده شده از شمش برنج با نقش قلم‌زنی اسلیمی ایرانی؛ ایده‌آل‌ترین ابزار برای ساییدن کلاله‌های زعفران بدون ایجاد حرارت یا از بین رفتن عطر.',
    packagingType: 'جعبه هاردباکس محافظ با فوم اختصاصی',
    crocinLevel: 0,
    safranalLevel: 0,
    picrocrocinLevel: 0,
    origin: 'اصفهان - هنر دست قلم‌زنان سنتی',
    harvestYear: '۱۴۰۳',
    inStock: true,
  },
];

export const BATCH_DATABASE: Record<string, BatchAnalysis> = {
  'ZR-2024-N1': {
    batchCode: 'ZR-2024-N1',
    productName: 'زعفران سوپر نگین ۱ مثقال کریستال',
    grade: 'Super Negin Grade 1 (صادراتی A++)',
    harvestLocation: 'قائنات - مزارع اسفدن (ارتفاع ۱۶۵۰ متری)',
    harvestDate: 'آبان ۱۴۰۳ (برداشت سپیده‌دم)',
    labTestDate: '۱۴ آذر ۱۴۰۳',
    crocin: 294.6, // Std > 220
    safranal: 38.4, // Std 30-50
    picrocrocin: 92.1, // Std > 70
    moisture: 6.2, // Max 10%
    foreignMatter: 0.08, // Max 0.5%
    microbiologyStatus: 'Certified Grade A+',
    labInspector: 'دکتر علیرضا کاظمی (آزمایشگاه اکرودیته استاندارد فردوس)',
    isoStandard: 'ISO 3632-1:2011 Category I',
    healthLicense: '۵۶/۲۱۸۹۳ - سازمان غذا و دارو',
  },
  'ZR-GIFT-SH': {
    batchCode: 'ZR-GIFT-SH',
    productName: 'پک هدیه فاخر شاه‌نشین',
    grade: 'Super Negin Premium Reserve',
    harvestLocation: 'قائنات - دشت بیهود',
    harvestDate: 'آبان ۱۴۰۳',
    labTestDate: '۲۰ آذر ۱۴۰۳',
    crocin: 292.0,
    safranal: 39.0,
    picrocrocin: 94.0,
    moisture: 5.9,
    foreignMatter: 0.05,
    microbiologyStatus: 'Certified Grade A+',
    labInspector: 'مهندس مریم خرم‌نیا (انستیتو گیاهان دارویی خراسان)',
    isoStandard: 'ISO 3632-1:2011 Category I',
    healthLicense: '۵۶/۲۱۹۰۴ - سازمان غذا و دارو',
  },
  'ZR-SR-01G': {
    batchCode: 'ZR-SR-01G',
    productName: 'زعفران سرگل ممتاز ۱ گرمی پاکتی',
    grade: 'Sargol All-Red Grade A',
    harvestLocation: 'خراسان جنوبی - قائنات مرکزی',
    harvestDate: 'آبان ۱۴۰۳',
    labTestDate: '۸ آذر ۱۴۰۳',
    crocin: 272.5,
    safranal: 36.8,
    picrocrocin: 88.0,
    moisture: 6.8,
    foreignMatter: 0.15,
    microbiologyStatus: 'Certified Grade A+',
    labInspector: 'آزمایشگاه کنترل کیفیت مرجع زرین',
    isoStandard: 'ISO 3632-1:2011 Category I',
    healthLicense: '۵۶/۱۸۴۵۰ - سازمان غذا و دارو',
  },
  'ZR-BOX-VIP5': {
    batchCode: 'ZR-BOX-VIP5',
    productName: 'جعبه خاتم و معرق صادراتی ۵ مثقال',
    grade: 'Ultra Super Negin Royal Select',
    harvestLocation: 'قائنات - باغات خضری دشت بیاض',
    harvestDate: 'آبان ۱۴۰۳ (چین اول)',
    labTestDate: '۲۵ آذر ۱۴۰۳',
    crocin: 298.2,
    safranal: 41.0,
    picrocrocin: 96.5,
    moisture: 5.5,
    foreignMatter: 0.02,
    microbiologyStatus: 'Certified Grade A+',
    labInspector: 'دکتر محمدرضا سجادی (مرکز تحقیقات زعفران ایران)',
    isoStandard: 'ISO 3632-1:2011 Category I (Royal Grade)',
    healthLicense: '۵۶/۲۲۰۱۵ - سازمان غذا و دارو',
  },
};

export const FAQ_ITEMS = [
  {
    id: 1,
    question: 'تفاوت زعفران سوپر نگین، سرگل و پوشال در چیست؟',
    answer: 'زعفران سوپر نگین تنها از درشت‌ترین و کشیده‌ترین سرشاخه‌های کلاله سه‌شاخه بدون ذره‌ای ریشه سفید (خامه) یا شکستگی به‌صورت اتویی و کاملاً صاف خشک می‌شود. سرگل تمام‌قرمز است اما طول کلاله‌ها کوتاه‌تر و ممکن است دارای دانه‌های خردشده باشد. پوشال دارای ۱ الی ۳ میلی‌متر بخش زرد/سفید انتهای کلاله است. سوپر نگین بالاترین کروسین (قدرت رنگ‌دهی بالای ۲۹۰) و نهایت جلوه تشریفاتی را داراست.',
  },
  {
    id: 2,
    question: 'روش صحیح دم‌آوری زعفران با شوک یخ چیست؟',
    answer: 'ابتدا کلاله‌های زعفران را در هاون برنجی به همراه مقدار بسیار اندکی قند یا شکر بسایید تا کاملاً نرم شود (هرگز بیش از حد داغ نسابید). سپس چند قطعه یخ کوچک روی پودر بریزید و اجازه دهید در دمای اتاق یخ ذوب شود. بعد از آب شدن یخ، به ازای هر مثقال، نصف استکان آب جوش اضافه نمایید. شوک حرارتی سرما به گرما باعث آزاد شدن حداکثر قدرت کروسین (رنگ یاقوتی) بدون فرار شدن اسانس روغنی سافرانال می‌شود.',
  },
  {
    id: 3,
    question: 'هر مثقال زعفران چند گرم است و برای چه تعداد نفر کافی است؟',
    answer: 'هر مثقال دقیقاً معادل ۴.۶۰۸۳ گرم است. به طور متوسط، ۱ گرم زعفران برای طبخ ۱۰ الی ۱۵ پرس برنج زعفرانی مجلسی کافی است. بنابراین ۱ مثقال زعفران اعلای زرین برای حدود ۵۰ الی ۷۰ پرس چلو، شله‌زرد یا دسرهای مهمانی بزرگ پاسخگو خواهد بود.',
  },
  {
    id: 4,
    question: 'نحوه استعلام گواهی آزمایشگاه و اطمینان از اصالت محصول چگونه است؟',
    answer: 'بر روی کلیه بسته‌بندی‌های زرین قائنات، یک برچسب امنیتی هولوگرام حاوی شماره بچ (مانند ZR-2024-N1) درج شده است. شما می‌توانید این کد را در سامانه آنلاین استعلام زرین وارد نموده و آنالیز کامل شامل درصد کروسین (رنگ)، سافرانال (عطر) و پیکروکروسین (طعم) تاییدشده توسط آزمایشگاه اکرودیته سازمان استاندارد را مشاهده فرمایید.',
  },
  {
    id: 5,
    question: 'شرایط نگهداری و مدت زمان ماندگاری عطر زعفران چقدر است؟',
    answer: 'زعفران را در ظروف کریستال یا شیشه‌ای دربسته با درپوش چوب‌پنبه یا فلزی در جای خشک، خنک و دور از تابش مستقیم خورشید نگهداری کنید. در این شرایط، عطر و خاصیت رنگ‌دهی زعفران زرین تا بیش از ۳ سال کاملاً تازه و دست‌نخورده حفظ می‌گردد.',
  },
];

export const TESTIMONIALS = [
  {
    id: 1,
    name: 'سرآشپز مریم طاهری',
    role: 'سرآشپز اجرایی هتل اسپیناس پالاس تهران',
    avatarInitials: 'م‌ط',
    rating: 5,
    comment: 'به عنوان سرآشپز اجرایی، ثبات رنگ و عطر زعفران در پلوهای تشریفاتی حیاتی است. چند رشته از سوپر نگین زرین با روش شوک یخ، رنگ سرخ یاقوتی بی‌نظیری ایجاد می‌کند که در هیچ برندی ندیده‌ام. بسته‌بندی کریستالی درب چوب‌پنبه هم عطر کلاله‌ها را تا آخرین ذره تازه نگه می‌دارد.',
  },
  {
    id: 2,
    name: 'دکتر سهراب اسکندری',
    role: 'مدیرعامل هلدینگ و سفارش‌دهنده پک‌های سازمانی',
    avatarInitials: 'س‌ا',
    rating: 5,
    comment: 'پک چوبی شاه‌نشین را برای هدیه به میهمانان و سفرای خارجی تهیه کردیم. بسته‌بندی نگارگری اصیل مینیاتور ایرانی همراه هاون برنجی دست‌ساز و شفافیت استعلام آزمایشگاه با کد رهگیری، نهایت اعتبار و اصالت را القا کرد. بازخوردها فوق‌العاده بود.',
  },
  {
    id: 3,
    name: 'نیلوفر پارسا',
    role: 'کارشناس شیرینی‌پزی و عضو وفادار باشگاه زرین',
    avatarInitials: 'ن‌پ',
    rating: 5,
    comment: 'زعفران‌های بازاری اغلب بوی کهنگی می‌دهند یا خاک دارند، اما زرین واقعاً رشته‌های سالم، یکدست و عطر زنده و غلیظ دارد. شله‌زرد و بستنی سنتی که با این زعفران درست کردم، عطر اصیل خانه مادربزرگ را زنده کرد.',
  },
];
